version: '3.1'

services:
  ihateline:
    restart: always
    build: . 
    volumes:
      - shared-volume:/tmp/shared
    depends_on:
      - chrome
    environment:
      - "TZ=Asia/Taipei"
      - "pixabay_key="
    command: python server.py
    logging:
      options:
        max-size: '10m'
        max-file: '3'
      driver: json-file
  chrome:
    image: selenium/standalone-chrome 
    volumes:
      - shared-volume:/tmp/shared
    shm_size: 4g
    ports:
      - 44444:4444
    environment:
      - "TZ=Asia/Taipei"
    logging:
      options:
        max-size: '10m'
        max-file: '3'
      driver: json-file
  cron:
    build: ./cron 
    depends_on:
      - ihateline
    volumes:
      - "./cron/crontabs:/etc/crontabs/root:ro"
    logging:
      options:
        max-size: '10m'
        max-file: '3'
      driver: json-file
volumes:
  shared-volume:
